package com.lhc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopping<M extends BaseShopping<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOwnerId(java.lang.Integer ownerId) {
		set("ownerId", ownerId);
	}
	
	public java.lang.Integer getOwnerId() {
		return getInt("ownerId");
	}
	
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setImg(java.lang.String img) {
		set("img", img);
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}
	
	public void setInfo(java.lang.String info) {
		set("info", info);
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setPrice(java.lang.String price) {
		set("price", price);
	}
	
	public java.lang.String getPrice() {
		return getStr("price");
	}
	
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return getDate("time");
	}
	
}

